### ISSUE TITLE
About SXSpider & SXSpider2(using selenium);

### ISSUE THREAD

**Issue by JunjieLeiCoe** [frederichchen/ToySpiders#1]
您好， 因为论文的需要，很早就开始关注您写的关于失信人的爬虫。 
但是我本地的运行过程中发现一些问题，希望解答。

---

* 首先是 SXSpider用的是Requests的包，我发现爬取的数据其实只有50个，我在想是不是百度的API 出现了问题，request 得到的url失效。
* 您的SXSpider_2 用的是Selenium，确实会比requests好非常多虽然速度上会比reuqests慢，抓取到的有效数据也会非常多， 但是本地大量抓去数据百度页面的时候会遇到一些卡顿。不知道这个是不是百度的反扒机制

**Comment by frederichchen** [comment]
您好，谢谢您的关注。第一个爬虫是我很早以前写的了，当时的 url 跟现在不一样了，百度现在的 AJAX 也加入了反爬虫机制，所以已经失效，所以我才写了第二版。不过我并没有进行大量的测试，您大概是爬到多少页以后出现的卡顿？大概是什么现象？能不能录个屏发给我看看以便我找出问题所在？


________________________________
发件人: JuNJiE <notifications@github.com>
发送时间: 2020年7月28日 6:11
收件人: frederichchen/ToySpiders <ToySpiders@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [frederichchen/ToySpiders] About SXSpider & SXSpider2(using selenium); (#1)


您好， 因为论文的需要，很早就开始关注您写的关于失信人的爬虫。
但是我本地的运行过程中发现一些问题，希望解答。

________________________________

  *   首先是 SXSpider用的是Requests的包，我发现爬取的数据其实只有50个，我在想是不是百度的API 出现了问题，request 得到的url失效。
  *   您的SXSpider_2 用的是Selenium，确实会比requests好非常多虽然速度上会比reuqests慢，抓取到的有效数据也会非常多， 但是本地大量抓去数据百度页面的时候会遇到一些卡顿。不知道这个是不是百度的反扒机制

―

**Comment by JunjieLeiCoe** [comment]
[Video Link](https://drive.google.com/file/d/1PodKyNv_0AbZSIzv7_AF2v9jVrVUCP_f/view?usp=sharing)
如视频里所示，175页开始，code在跑，页数也在叠加，但是每一页显示的被执行人却 没有变。 
<br>
<img width="2036" alt="Screen Shot 2020-07-27 at 11 51 21 PM" src="https://user-images.githubusercontent.com/46977478/88629427-18d2da00-d064-11ea-9e8e-ea1ede729274.png">
<br>
<img width="2046" alt="Screen Shot 2020-07-27 at 11 51 00 PM" src="https://user-images.githubusercontent.com/46977478/88629448-21c3ab80-d064-11ea-91f0-b4bce2b1c707.png">

**Comment by frederichchen** [comment]
您好，我重新改写了一下程序，测试了前200页没问题了。麻烦您重新帮我测试一下SXSpider2，如果出现视频那种情况，您可以手动点击一下公告列表中的“展开详情”，应该就可以了。
