### ISSUE TITLE
大佬，这个准确的如何？可以上生产环境用吗？

### ISSUE THREAD

**Issue by cole1993** [frederichchen/ToySpiders#2]
大佬，这个准确的如何？可以上生产环境用吗？

**Comment by frederichchen** [comment]
失信被执行人的SXSpider2我自己只测试了爬取前两百页，没有测更多了，就前两百页的情况来看，还是能准确爬下来的，但至于说爬取更多以后会不会遭遇反爬虫机制或者出现其他什么问题就不知道了。这个本身就是自己写的很简陋的玩具小爬虫程序，不敢保证能用在生产环境上。
